### ISSUE TITLE
com.intellij.lexer does not exist

### ISSUE THREAD

**Issue by ftomassetti** [Dierk/frege-idea-plugin#1]
I get a few errors when trying to build this project. Should I configure something? Can you provide instructions in the README?

**Comment by Dierk** [comment]
Hi,

Cool to see someone working with it. 
Please note that it is still very basic. 

In order to make things run, follow the "custom language support tutorial". The link is in the readme. 

Cheers
Dierk

sent from:mobile

**Comment by ftomassetti** [comment]
Hi Dierk,
I am trying to follow the instruction on http://confluence.jetbrains.com/display/IntelliJIDEA/Prerequisites and they are quite unclear to me:

```Configure a common JDK and an IntelliJ IDEA Plugin SDK. For IntelliJ IDEA Plugin SDK you should specify the directory with installed IntelliJ IDEA. By default it offers the directory of the currently running IntelliJ IDEA.

For IntelliJ IDEA Plugin SDK specify the directory with Community Edition source files.```

So, I have to specify 2 SDKs for the project: the Java SDK and the "Intellj Platform Plugin SDK". Now it is unclear which directory I should pick: the directory where idea is installed or the idea sources cloned at the previous step? I can just choose the former (if I choose the directory with the sources I got an error) and so I am confused about how to use the sources I have downloaded.

Can you help me figuring this out?

**Comment by Dierk** [comment]
Hi Federico,

yes, I remember having experienced the same confusion.

Not sure whether my solution is the best, but it worked for me:
I used the IDEA IU-138.2210.3 SDK from my IDEA 13 installation directory.

But if you find any other solution that works, that should be fine as well.

fingers crossed
Dierk

**Comment by ftomassetti** [comment]
Ok, when opening this project I had first to add the SDKs under Platform Settings, then I had to select this SDK in Project Settings (otherwise it used the JDK as SDK)

**Comment by rahulsom** [comment]
@ftomassetti It should be simpler now with the gradle-ization to get the right class path. Let me know if that still causes problems.

https://github.com/Dierk/frege-idea-plugin/pull/2 has some details on it.
